default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password:

development:
  <<: *default
  database: todo_dev

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
